{% set name = "pymmcore-plus" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore_plus-{{ version }}.tar.gz
  sha256: 950c23beb5f39c7f8cd2591a30983706e19f7f18da5dba2723ddfb7de5d99de0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mmcore = pymmcore_plus._cli:main

requirements:
  host:
    - python >=3.8
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy
    - platformdirs >=3.0.0
    - psygnal >=0.7.0
    - pymmcore >=10.7.0.71.0
    - qtpy >=2
    - rich >=10.2.0
    - typer >=0.4.2
    - typing-extensions
    - useq-schema >=0.4.7
    - wrapt >=1.14

test:
  imports:
    - pymmcore_plus
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymmcore-plus
  summary: A convenience layer on pymmcore (micro-manager) providing improved python UX and event management
  dev_url: https://github.com/pymmcore-plus/pymmcore-plus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
