{% set name = "pymmcore-plus" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore_plus-{{ version }}.tar.gz
  sha256: 0a397ef3aba7fb69e096b56b9842c17eec901967e57cb625b396306fc7e251eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8
    - loguru
    - numpy
    - psygnal >=0.4.2
    - pymmcore >=10.1.1.70.4
    - typing-extensions
    - useq-schema
    - wrapt

    # Remote stuff
    # - pyro5 >=5.10
    # - msgpack-python
    # - psutil

test:
  imports:
    - pymmcore_plus
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/pymmcore-plus
  summary: Control pymmcore (micro-manager) in another process
  dev_url: https://github.com/tlambert03/pymmcore-plus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
