{% set name = "pymmcore-plus" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore_plus-{{ version }}.tar.gz
  sha256: 10adc6c8456ac650b009a623c28ceceb9dbad6593fab31e698c2712cd2eaea14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - loguru
    - msgpack-python
    - numpy
    - psutil
    - psygnal
    - pymmcore >=10.1.1.70.4
    - pyro5 >=5.10
    - python >=3.8
    - typing-extensions
    - useq-schema

test:
  imports:
    - pymmcore_plus
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/pymmcore-plus
  summary: Control pymmcore (micro-manager) in another process
  dev_url: https://github.com/tlambert03/pymmcore-plus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
