{% set name = "pymmcore-plus" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore_plus-{{ version }}.tar.gz
  sha256: 54b8c80e3f800694f4aaf7582d3e7937d1da19999da540aedaf586d1d414daf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mmcore = pymmcore_plus._cli:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - appdirs
    - numpy
    - psygnal >=0.4.2
    - pymmcore >=10.1.1.70.4
    - python >=3.8
    - qtpy
    - rich >=10.2.0
    - typer >=0.4.2
    - typing-extensions
    - useq-schema >=0.4.0
    - wrapt

test:
  imports:
    - pymmcore_plus
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymmcore-plus
  summary: A convenience layer on pymmcore (micro-manager) providing improved python UX and event management
  dev_url: https://github.com/pymmcore-plus/pymmcore-plus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
